from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from time import perf_counter
from typing import TYPE_CHECKING, TypeAlias

import jax
import numpy as np
from loguru import logger
from numpy.typing import NDArray

from pyticc._typing import JaxDevice
from pyticc.matrix.interaction.diabatic_atom_diatom import DiabaticVGridBF
from pyticc.propagation.grid import RadialSector, build_radial_sectors

if TYPE_CHECKING:
    from pyticc.system import ScatteringType, ScattSystem

PotentialValues: TypeAlias = NDArray[np.float64] | NDArray[np.complex128] | DiabaticVGridBF
DevicePotentialValues: TypeAlias = jax.Array | DiabaticVGridBF
NamedGridArrays: TypeAlias = tuple[tuple[str, NDArray[np.float64]], ...]


# ----------------------------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class PotentialGrid:
    """Raw interaction-potential values on one complete propagation grid.

    Members:
        boundaries: tuple[float,...] - radial interval boundaries in bohr
        half_steps: tuple[float,...] - nominal propagation half-steps in bohr
        sectors: tuple[RadialSector,...] - sectors generated by
            ``build_radial_sectors(boundaries,half_steps)``
        radial_points: NDArray[np.float64] - ordered sector endpoints and
            midpoints, shape ``(2*n_sector+1,)``
        scattering_type: ScatteringType - geometry and potential representation
        coordinates: NamedGridArrays - named internal-coordinate nodes
        weights: NamedGridArrays - named quadrature weights
        values: PotentialValues - scalar, Lambda, or diabatic raw PES values
            with ``radial_points`` as the leading axis
        _device_cache: dict[tuple[str,int],DevicePotentialValues] - complete raw
            PES values copied once to each requested JAX device
    """

    boundaries: tuple[float, ...]
    half_steps: tuple[float, ...]
    sectors: tuple[RadialSector, ...]
    radial_points: NDArray[np.float64]
    scattering_type: ScatteringType
    coordinates: NamedGridArrays
    weights: NamedGridArrays
    values: PotentialValues
    _device_cache: dict[tuple[str, int], DevicePotentialValues] = field(default_factory=dict, init=False, repr=False, compare=False)

    @property
    def Rmatch(self) -> float:
        """Return the final radial matching point in bohr."""
        return self.sectors[-1].radial_end

    def coordinate(self, name: str) -> NDArray[np.float64]:
        """Return one named internal-coordinate array."""
        return self._named_array(self.coordinates, name, "coordinate")

    def weight(self, name: str) -> NDArray[np.float64]:
        """Return one named quadrature-weight array."""
        return self._named_array(self.weights, name, "weight")

    def take(self, radial_points: float | Sequence[float] | NDArray[np.float64]) -> PotentialValues:
        """Return cached raw PES values at the requested radial points.

        Inputs:
            radial_points: float | Sequence[float] | NDArray[np.float64] - one
                radial point or an ordered one-dimensional radial batch in bohr

        Returns:
            values: PotentialValues - cached raw values with scalar or radial-
                batch shape matching ``radial_points``
        """
        selection = self._selection(radial_points)
        if isinstance(self.values, DiabaticVGridBF):
            return DiabaticVGridBF(
                diagonal=tuple(values[selection] for values in self.values.diagonal),
                coupling=self.values.coupling[selection],
            )
        return self.values[selection]

    def take_device(
        self,
        radial_points: float | Sequence[float] | NDArray[np.float64],
        device: JaxDevice,
    ) -> DevicePotentialValues:
        """Return cached raw PES values sliced directly on one JAX device.

        Inputs:
            radial_points: float | Sequence[float] | NDArray[np.float64] - one
                radial point or ordered one-dimensional radial batch in bohr
            device: JaxDevice - destination contraction device

        Returns:
            values: DevicePotentialValues - device-resident raw PES slice
        """
        key = (device.platform, device.id)
        values = self._device_cache.get(key)
        if values is None:
            if isinstance(self.values, DiabaticVGridBF):
                values = DiabaticVGridBF(
                    diagonal=tuple(jax.device_put(array, device) for array in self.values.diagonal),
                    coupling=jax.device_put(self.values.coupling, device),
                )
            else:
                values = jax.device_put(self.values, device)
            self._device_cache[key] = values
            logger.info(f"Potential grid resident on {device.platform}:{device.id}, size={self._size_mib():.1f} MiB")

        selection = self._selection(radial_points)
        if isinstance(values, DiabaticVGridBF):
            return DiabaticVGridBF(
                diagonal=tuple(array[selection] for array in values.diagonal),
                coupling=values.coupling[selection],
            )
        return values[selection]

    def _selection(
        self,
        radial_points: float | Sequence[float] | NDArray[np.float64],
    ) -> int | NDArray[np.int64]:
        """Return complete-grid indices for requested radial points."""
        requested = np.asarray(radial_points, dtype=np.float64)
        if requested.ndim > 1:
            message = f"radial_points must be scalar or one-dimensional, but got shape {requested.shape}"
            logger.error(message)
            raise ValueError(message)

        flattened = requested.reshape(-1)
        positions = np.searchsorted(self.radial_points, flattened)
        inside = positions < self.radial_points.size
        matched = np.zeros(flattened.size, dtype=bool)
        matched[inside] = np.isclose(self.radial_points[positions[inside]], flattened[inside], rtol=0.0, atol=1.0e-12)
        if not np.all(matched):
            missing = flattened[~matched]
            message = f"Potential grid does not contain radial points {missing.tolist()}"
            logger.error(message)
            raise ValueError(message)
        return int(positions[0]) if requested.ndim == 0 else positions.astype(np.int64)

    def _size_mib(self) -> float:
        """Return the complete raw PES size in MiB."""
        if isinstance(self.values, DiabaticVGridBF):
            size = sum(array.nbytes for array in self.values.diagonal) + self.values.coupling.nbytes
        else:
            size = self.values.nbytes
        return size / 1024**2

    @staticmethod
    def _named_array(arrays: NamedGridArrays, name: str, label: str) -> NDArray[np.float64]:
        """Return one array from a compact named-array tuple."""
        for array_name, values in arrays:
            if array_name == name:
                return values
        message = f"Potential grid has no {label} named {name!r}"
        logger.error(message)
        raise KeyError(message)


# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
def _require_type(potential_grid: PotentialGrid, scattering_type: ScatteringType) -> None:
    """Require one geometry-specific potential-grid representation."""
    if potential_grid.scattering_type is not scattering_type:
        message = f"Expected a {scattering_type.value} potential grid, but got {potential_grid.scattering_type.value}"
        logger.error(message)
        raise TypeError(message)


# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
def prepare_potential(
    system: ScattSystem,
    boundaries: Sequence[float],
    half_steps: Sequence[float],
    *,
    processes: int = 1,
    **quadrature: int | bool | None,
) -> PotentialGrid:
    """Prepare the geometry-specific raw PES grid for one scattering system.

    Inputs:
        system: ScattSystem - prepared fixed-arrangement scattering system
        boundaries: Sequence[float] - radial interval boundaries in bohr
        half_steps: Sequence[float] - propagation half-step in each interval
        processes: int - worker processes used for the radial PES batch
        quadrature: int | bool | None - geometry-specific quadrature options

    Returns:
        potential_grid: PotentialGrid - raw PES values on all propagation points
    """
    from pyticc.scattering.model import get_scattering_model
    from pyticc.system import ScattSystem

    if not isinstance(system, ScattSystem):
        message = "prepare_potential requires a ScattSystem"
        logger.error(message)
        raise TypeError(message)

    if system.scattering_type is None:
        message = "prepare_potential requires a system built with an explicit scattering_type"
        logger.error(message)
        raise TypeError(message)
    n_radial_points = 2 * len(build_radial_sectors(boundaries, half_steps)) + 1
    started = perf_counter()
    logger.info(f"Potential preparation started: type={system.scattering_type.value}, radial_points={n_radial_points}, processes={processes}")
    model = get_scattering_model(system.scattering_type)
    potential_grid = model.prepare_potential(system, boundaries, half_steps, processes=processes, **quadrature)
    logger.info(
        f"Potential preparation complete: type={system.scattering_type.value}, radial_points={n_radial_points}, wall={perf_counter() - started:.3f} s"
    )
    return potential_grid


# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
def _potential_radial_grid(
    boundaries: Sequence[float],
    half_steps: Sequence[float],
) -> tuple[tuple[float, ...], tuple[float, ...], tuple[RadialSector, ...], NDArray[np.float64]]:
    """Build sectors and their ordered unique endpoint/midpoint support."""
    boundary_values = tuple(float(value) for value in boundaries)
    half_step_values = tuple(float(value) for value in half_steps)
    sectors = build_radial_sectors(boundary_values, half_step_values)
    radial_points = np.empty(2 * len(sectors) + 1, dtype=np.float64)
    radial_points[0] = sectors[0].radial_start
    for index, sector in enumerate(sectors):
        radial_points[2 * index + 1] = sector.radial_mid
        radial_points[2 * index + 2] = sector.radial_end
    return boundary_values, half_step_values, sectors, radial_points


# ----------------------------------------------------------------------------------------
